"""add lost and found qr table

Revision ID: 95a88cff1004
Revises: 304eb8629c4f
Create Date: 2025-08-21 21:27:23.759482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a88cff1004'
down_revision: Union[str, Sequence[str], None] = '304eb8629c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_and_found_qr', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('lost_and_found_qr', sa.Column('phone_number', sa.String(length=50), nullable=False))
    op.add_column('lost_and_found_qr', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('lost_and_found_qr', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('lost_and_found_qr', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('lost_and_found_qr', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('lost_and_found_qr', sa.Column('send_location_on_scan', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'lost_and_found_qr', ['qr_id'])
    op.drop_column('lost_and_found_qr', 'contact_info')
    op.drop_column('lost_and_found_qr', 'location')
    op.drop_column('lost_and_found_qr', 'description')
    op.drop_column('lost_and_found_qr', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_and_found_qr', sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('lost_and_found_qr', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lost_and_found_qr', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('lost_and_found_qr', sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lost_and_found_qr', type_='unique')
    op.drop_column('lost_and_found_qr', 'send_location_on_scan')
    op.drop_column('lost_and_found_qr', 'website')
    op.drop_column('lost_and_found_qr', 'company')
    op.drop_column('lost_and_found_qr', 'email')
    op.drop_column('lost_and_found_qr', 'address')
    op.drop_column('lost_and_found_qr', 'phone_number')
    op.drop_column('lost_and_found_qr', 'full_name')
    # ### end Alembic commands ###
