"""initial migration

Revision ID: c48cf7413ada
Revises: 
Create Date: 2025-08-21 21:13:28.779258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48cf7413ada'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_designs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('qr_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('error_correction', sa.String(length=10), nullable=True),
    sa.Column('border', sa.Integer(), nullable=True),
    sa.Column('foreground_color', sa.String(length=7), nullable=True),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('content_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qr_design_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['qr_design_id'], ['qr_designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qr_design_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['qr_design_id'], ['qr_designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_code_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qr_design_id', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['qr_design_id'], ['qr_designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_code_usage')
    op.drop_table('design_images')
    op.drop_table('content_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('qr_designs')
    # ### end Alembic commands ###
